language: ruby
rvm:
- 2.1.0
script:
- bundle exec rake generate
before_deploy: "cd public"
deploy:
  provider: cloudfiles
  username: floppy
  api_key:
    secure: dUm2oP4e7ij8jHcOBhe3mNNh5dpJramUstqQVaF/VfOLxIv6OQw+nWAOPo/Jl5tTmYQcsrz2FokHsHVc9RCjtNgWbI0+lMvbgFFlBpNohytkxMj9SOZ34c6arpsGS5CoP7OdhZgWhDizolcumB5yYA8tOcveNvQeGRusSYM6Ojg=
  region: LON
  container: floppy.org.uk
  on:
    repo: Floppy/floppy.github.io
    branch: source
