# ----------------------- #
#      Main Configs       #
# ----------------------- #

title: James Smith
subtitle: Building a better future out of code
author: James Smith
simple_search: http://google.com/search
description:
include: [.well-known]

date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:

# RSS feeds can list your email address if you like
email: james@floppy.org.uk

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

permalink: /blog/:year/:month/:day/:title/
code_dir: downloads/code
category_dir: blog/categories
markdown: kramdown

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  
paginate: 3           # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: Floppy
github_repo_count: 5
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: floppy
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 106927026319199661821
googleplus_hidden: false

# Disqus Comments
disqus_short_name: floppyorguk
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-2310810-2

## Theme settings

# navigation

navigation:
- text: Home
  url: /
- text: Archive
  url: /blog/archives
- text: Code
  url: /code
