# ----------------------- #
#      Main Configs       #
# ----------------------- #

version: 3.0.3
title: James Smith
subtitle: Building a better future out of code
author: James Smith
simple_search: https://google.com/search
description:
include: [.well-known]
exclude: [vendor]

date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:

# RSS feeds can list your email address if you like
email: james@floppy.org.uk

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

permalink: /blog/:year/:month/:day/:title/
markdown: kramdown

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

titlecase: true       # Converts page and post titles to titlecase

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: Floppy

# Keybase.io
keybase_user: floppy

# Twitter
twitter_user: floppy
twitter_tweet_button: true

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 106927026319199661821
googleplus_hidden: false

# Google Analytics
google_analytics_tracking_id: UA-2310810-2

## Theme settings

# navigation

navigation:
- text: Home
  url: /
- text: Blog
  url: /blog
- text: Talks
  url: /talks
- text: Projects
  url: /projects
- text: CV
  url: /cv

collections:
  talks:
    output: true
    permalink: /talks/:year/:month/:day/:title/
    
defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
